// Puzzle data and utilities
export const puzzles = [
  // Level 1-9: Standard Puzzles
  {
    id: 1,
    type: "pattern",
    title: "Neural Pattern Recognition",
    story: "Level 01: The Vault awakens. Identify the anomaly.",
    question: "Which symbol does NOT follow the same rotational symmetry?",
    options: ["▲", "◆", "◇", "▲", "▲"],
    answer: "◇",
    hint: "Symmetry betrays itself when mirrored. Which impostor breaks the reflection?",
    clue: "CHRONO",
    time: 30,
    difficulty: "easy",
  },
  {
    id: 2,
    type: "cipher",
    title: "Broken Language",
    story: "Level 02: The letters are scrambled by time.",
    question: "Decode the scrambled word: E T I M (Order based on clockwise alphabet positions)",
    answer: "TIME",
    hint: "Alphabets spiral. What order does displacement demand?",
    clue: "CIPHER",
    time: 30,
    difficulty: "easy",
  },
  {
    id: 3,
    type: "logic",
    title: "Boundary Logic",
    story: "Level 03: The system questions universals.",
    question: "If the statement 'All swans are white' is false, does a non-white swan exist?",
    answer: "YES",
    hint: "Negating a universal statement implies at least one counterexample.",
    clue: "VAULT",
    time: 50,
    difficulty: "medium",
  },
  {
    id: 4,
    type: "audio/morse",
    title: "Silent Signal",
    story: "Level 04: A forgotten distress call echoes.",
    question: "Solve: ... --- ...",
    answer: "SOS",
    hint: "Desperation speaks in rhythmic silence. Decipher the code of distress.",
    clue: "SEALED",
    time: 40,
    difficulty: "medium",
  },
  {
    id: 5,
    type: "reverse",
    title: "Paradox Chamber",
    story: "Level 05: Logic bends. Instructions lie.",
    question: "To continue, type the OPPOSITE of 'RIGHT'.",
    answer: "LEFT",
    hint: "When instructions lie, what remains true? Inversion is not always obvious.",
    clue: "BEYOND",
    time: 30,
    difficulty: "medium",
  },
  {
    id: 6,
    type: "cipher",
    title: "Caesar Lock",
    story: "Level 06: Letters rewind through time.",
    question: "ROT‒5 Cipher: FXYM → ?",
    answer: "BTSH",
    hint: "Caesar walked backward through time. How many steps did he retreat?",
    clue: "REALITY",
    time: 45,
    difficulty: "medium",
  },
  {
    id: 7,
    type: "visual",
    title: "Constellation Memory",
    story: "Level 07: Stars form patterns — not randomness.",
    question: "Which constellation contains the three aligned stars known as 'The Belt'?",
    answer: "ORION",
    hint: "Hunter of the night sky.",
    clue: "FRACTURE",
    time: 40,
    difficulty: "medium",
  },
  {
    id: 8,
    type: "binary",
    title: "Digital Consciousness",
    story: "Level 08: Machines whisper truth.",
    question: "01010100 01001001 01001101 01000101",
    answer: "TIME",
    hint: "ASCII. Group letters.",
    clue: "BETWEEN",
    time: 50,
    difficulty: "hard",
  },
  {
    id: 9,
    type: "riddle",
    title: "Temporal Riddle",
    story: "Level 09: Time mocks memory.",
    question: "It runs, but never walks. It murmurs, but never talks.",
    answer: "RIVER",
    hint: "Always moving.",
    clue: "WORLDS",
    time: 40,
    difficulty: "hard",
  },

  // Level 10: MINI-GAME - Sudoku
  {
    id: 10,
    type: "minigame_sudoku",
    title: "Quantum Sudoku",
    story: "Level 10: Numbers align in the quantum realm.",
    question: "Complete the 4x4 Sudoku grid",
    answer: "1234214334121423", // Flattened solution
    hint: "Each row, column, and 2x2 box needs 1-4.",
    clue: "HIDDEN",
    time: 120,
    difficulty: "hard",
    puzzleGrid: [
      [0, 0, 0, 4],
      [0, 0, 2, 0],
      [3, 0, 0, 0],
      [0, 2, 0, 0],
    ],
    solution: [
      [2, 1, 3, 4],
      [4, 3, 2, 1],
      [3, 4, 1, 2],
      [1, 2, 4, 3],
    ],
  },

  // Level 11-19: Standard Puzzles
  {
    id: 11,
    type: "anagram",
    title: "Forgotten Name",
    story: "Level 11: Rearrange time.",
    question: "Anagram: 'NOMAEG'",
    answer: "OMEGAN",
    hint: "Last letter of the Greek alphabet… but twisted.",
    clue: "PORTAL",
    time: 40,
    difficulty: "medium",
  },
  {
    id: 12,
    type: "logic",
    title: "Alien Inference",
    story: "Level 12: Symbols speak in implications.",
    question: "If ★ implies ☽ and ★ is true, is ☽ true?",
    answer: "YES",
    hint: "Use modus ponens: implication + antecedent gives the consequent.",
    clue: "AWAITS",
    time: 45,
    difficulty: "medium",
  },
  {
    id: 13,
    type: "visual",
    title: "Ancient Glyphs",
    story: "Level 13: Symbols speak silently.",
    question: "☼=Sun, ☾=Moon, 🜂=Fire, 🜄=?",
    answer: "WATER",
    hint: "Opposite of fire.",
    clue: "THOSE",
    time: 45,
    difficulty: "medium",
  },
  {
    id: 14,
    type: "memory",
    title: "Recall the Past",
    story: "Level 14: Time tests memory.",
    question: "What was the answer to Level 4?",
    answer: "SOS",
    hint: "A repeated plea.",
    clue: "BRAVE",
    time: 45,
    difficulty: "easy",
  },
  {
    id: 15,
    type: "direction",
    title: "Compass Lock",
    story: "Level 15: Orient or be lost.",
    question: "Opposite of WEST?",
    answer: "EAST",
    hint: "Sunrise.",
    clue: "ENOUGH",
    time: 40,
    difficulty: "easy",
  },
  {
    id: 16,
    type: "logic",
    title: "Temporal Recursion",
    story: "Level 16: Functions collapse into themselves.",
    question: "If f(n) = 2^n - 1, and f(f(2)) = ?",
    answer: "15",
    hint: "Apply the function twice. Does the void echo itself?",
    clue: "ESCAPE",
    time: 45,
    difficulty: "hard",
  },
  {
    id: 17,
    type: "deduction",
    title: "Orbital Truth",
    story: "Level 17: Only one sustains life.",
    question: "Third planet from the Sun?",
    answer: "EARTH",
    hint: "Blue planet.",
    clue: "VOID",
    time: 45,
    difficulty: "easy",
  },
  {
    id: 18,
    type: "cipher",
    title: "Runic Encryption",
    story: "Level 18: The ancients wrote differently.",
    question: "ᚺᛁ → ? (Elder Futhark)",
    answer: "HI",
    hint: "Runes equal letters.",
    clue: "FIND",
    time: 45,
    difficulty: "hard",
  },
  {
    id: 19,
    type: "counting",
    title: "Temporal Measure",
    story: "Level 19: Count precisely.",
    question: 'Count characters: "CHRONOCIPHER"',
    answer: "12",
    hint: "Double-check.",
    clue: "EXIT",
    time: 50,
    difficulty: "easy",
  },

  // Level 20: MINI-GAME - Pattern Match
  {
    id: 20,
    type: "minigame_pattern",
    title: "Neural Network",
    story: "Level 20: Patterns cascade through layers.",
    question: "Match all pairs in 30 seconds",
    answer: "PERFECT",
    hint: "Memory and speed.",
    clue: "NEXUS",
    time: 120,
    difficulty: "hard",
    patterns: [
      { id: 1, symbol: "◆", color: "cyan" },
      { id: 2, symbol: "◇", color: "purple" },
      { id: 3, symbol: "★", color: "cyan" },
      { id: 4, symbol: "✚", color: "purple" },
      { id: 1, symbol: "◆", color: "cyan" },
      { id: 2, symbol: "◇", color: "purple" },
      { id: 3, symbol: "★", color: "cyan" },
      { id: 4, symbol: "✚", color: "purple" },
    ],
  },

  // Level 21-29: Standard Puzzles
  {
    id: 21,
    type: "logic",
    title: "Truth Table Lock",
    story: "Level 21: Nothing is true. Everything is logic.",
    question: "IF (A=true, B=false) and (A && B = ?)",
    answer: "FALSE",
    hint: "Both must be true.",
    clue: "SPIRAL",
    time: 45,
    difficulty: "hard",
  },
  {
    id: 22,
    type: "visual",
    title: "Silhouette Recall",
    story: "Level 22: Shadows hold secrets.",
    question: "What animal has a long neck and spots?",
    answer: "GIRAFFE",
    hint: "African mammal.",
    clue: "SHADOW",
    time: 50,
    difficulty: "easy",
  },
  {
    id: 23,
    type: "cipher",
    title: "Atbash Mirror",
    story: "Level 23: Mirrors reflect truth.",
    question: "Atbash cipher decode: ZYXWVUTSRQ → ?",
    answer: "ABCDEFGHIJ",
    hint: "A=Z, B=Y, etc.",
    clue: "MIRROR",
    time: 45,
    difficulty: "hard",
  },
  {
    id: 24,
    type: "logic",
    title: "Contrapositive",
    story: "Level 24: Reasoning reveals hidden structure.",
    question: "If P implies Q, and Q is false, what can you infer about P? (True/False)",
    answer: "FALSE",
    hint: "Use the contrapositive: not Q implies not P.",
    clue: "HARMONY",
    time: 50,
    difficulty: "medium",
  },
  {
    id: 25,
    type: "riddle",
    title: "Temporal Paradox",
    story: "Level 25: Time folds on itself.",
    question: "What travels around the world but stays in a corner?",
    answer: "STAMP",
    hint: "Mail marker.",
    clue: "CORNER",
    time: 50,
    difficulty: "medium",
  },
  {
    id: 26,
    type: "logic",
    title: "Trio Truths",
    story: "Level 26: Limited truths constrain the system.",
    question: "Exactly two of A, B, C are true. If A is false, are B and C both true?",
    answer: "YES",
    hint: "If exactly two are true and A is false the remaining two must be true.",
    clue: "QUANTUM",
    time: 40,
    difficulty: "medium",
  },
  {
    id: 27,
    type: "visual",
    title: "Grid Logic",
    story: "Level 27: Grids hold geometry.",
    question: "In a 3x3 grid, how many 2x2 squares exist?",
    answer: "4",
    hint: "Think about overlapping.",
    clue: "GEOMETRY",
    time: 50,
    difficulty: "medium",
  },
  {
    id: 28,
    type: "cipher",
    title: "Vigenère Echo",
    story: "Level 28: Cipher repeats.",
    question: "Vigenère (key='KEY'): PLAINTEXT → ? (first 5 letters)",
    answer: "ZIHVL",
    hint: "Repeating key cipher.",
    clue: "CIPHER",
    time: 50,
    difficulty: "hard",
  },
  {
    id: 29,
    type: "deduction",
    title: "Logic Chain",
    story: "Level 29: Deduction bridges gaps.",
    question: "All cats are mammals. Fluffy is a cat. Is Fluffy a mammal?",
    answer: "YES",
    hint: "Logical inference.",
    clue: "LOGIC",
    time: 45,
    difficulty: "easy",
  },

  // Level 30: MINI-GAME - Puzzle
  {
    id: 30,
    type: "minigame_puzzle",
    title: "Fragment Assembly",
    story: "Level 30: Broken pieces restore the image.",
    question: "Arrange fragments to reveal the symbol",
    answer: "COMPLETE",
    hint: "Focus on edges.",
    clue: "FRAGMENT",
    time: 120,
    difficulty: "hard",
    fragments: ["⬜", "⬛", "⬜", "⬛", "⬛", "⬜", "⬜", "⬛", "⬛"], // 3x3 pattern
    fragmentPositions: [0, 1, 2, 3, 4, 5, 6, 7, 8],
    correctOrder: [0, 1, 2, 3, 4, 5, 6, 7, 8],
  },

  // Level 31-39: Standard Puzzles
  {
    id: 31,
    type: "pattern",
    title: "Fractal Recognition",
    story: "Level 31: Patterns repeat infinitely.",
    question: "What comes next: L, LL, LLL, ____",
    answer: "LLLL",
    hint: "Each adds one.",
    clue: "FRACTAL",
    time: 45,
    difficulty: "easy",
  },
  {
    id: 32,
    type: "audio/morse",
    title: "Quantum Transmission",
    story: "Level 32: Signals cross dimensions.",
    question: "Decode: .... . .-.. .-.. ---",
    answer: "HELLO",
    hint: "International Morse Code.",
    clue: "SIGNAL",
    time: 50,
    difficulty: "hard",
  },
  {
    id: 33,
    type: "visual",
    title: "Color Harmony",
    story: "Level 33: Colors sing together.",
    question: "Which color is NOT in the standard RGB model?",
    answer: "CYAN",
    hint: "Primary colors are Red, Green, Blue.",
    clue: "COLOR",
    time: 50,
    difficulty: "medium",
  },
  {
    id: 34,
    type: "logic",
    title: "Set Theory",
    story: "Level 34: Groups define existence.",
    question: "Element {2} is part of {{1},{2,3}}. True or False?",
    answer: "FALSE",
    hint: "Set membership vs element membership.",
    clue: "THEORY",
    time: 45,
    difficulty: "hard",
  },
  {
    id: 35,
    type: "riddle",
    title: "Existence Paradox",
    story: "Level 35: Some things cannot be.",
    question: "I speak without a mouth and hear without ears. I have no body, but come alive with wind.",
    answer: "ECHO",
    hint: "Sound phenomenon.",
    clue: "ECHO",
    time: 40,
    difficulty: "medium",
  },
  {
    id: 36,
    type: "sequence",
    title: "Palindrome Reversal",
    story: "Level 36: Reading forward and backward.",
    question: "Next palindrome after 121?",
    answer: "131",
    hint: "Numbers that read the same both ways.",
    clue: "PALINDROME",
    time: 50,
    difficulty: "medium",
  },
  {
    id: 37,
    type: "cipher",
    title: "ROT13 Reversal",
    story: "Level 37: Half rotations complete.",
    question: "ROT13: uryyb → ?",
    answer: "HELLO",
    hint: "13 letter shift.",
    clue: "ROTATION",
    time: 45,
    difficulty: "easy",
  },
  {
    id: 38,
    type: "logic",
    title: "Analogy",
    story: "Level 38: Relations mirror meaning.",
    question: "KING is to QUEEN as MAN is to ?",
    answer: "WOMAN",
    hint: "Think about counterpart roles in analogy.",
    clue: "GOLDEN",
    time: 45,
    difficulty: "medium",
  },
  {
    id: 39,
    type: "memory",
    title: "Archive Scan",
    story: "Level 39: Deep memory access.",
    question: "What was the clue from Level 15?",
    answer: "ENOUGH",
    hint: "A direction word.",
    clue: "MEMORY",
    time: 50,
    difficulty: "medium",
  },

  // Level 40: MINI-GAME - Maze Puzzle
  {
    id: 40,
    type: "minigame_maze",
    title: "Void Navigation",
    story: "Level 40: Navigate through the dimensional fracture.",
    question: "Find your way through the corrupted maze to escape",
    answer: "VICTORY",
    hint: "The path reveals itself to those who observe carefully.",
    clue: "LABYRINTH",
    time: 120,
    difficulty: "hard",
    gridSize: 10,
    walls: [
      [1, 2], [1, 3], [1, 4], [1, 5], [1, 6],
      [3, 1], [3, 2], [3, 4], [3, 5], [3, 6], [3, 7],
      [5, 2], [5, 3], [5, 4], [5, 6], [5, 7],
      [7, 1], [7, 3], [7, 4], [7, 5], [7, 8],
    ],
  },

  // Level 41: MINI-GAME - Simon Color Memory
  {
    id: 41,
    type: "minigame_simon",
    title: "Chrome Recall",
    story: "Level 41: The machine tests your memory.",
    question: "Repeat the color sequence through 5 levels",
    answer: "VICTORY",
    hint: "Watch each color and repeat it.",
    clue: "MEMORY",
    time: 120,
    difficulty: "hard",
  },

  // Level 42: MINI-GAME - Breakout Brick Breaker
  {
    id: 42,
    type: "minigame_breakout",
    title: "Barrier Collapse",
    story: "Level 42: Break through the walls of time.",
    question: "Destroy all 18 bricks with your paddle",
    answer: "VICTORY",
    hint: "Move your paddle to bounce the ball.",
    clue: "BREAKTHROUGH",
    time: 120,
    difficulty: "hard",
  },

  // Level 43: MINI-GAME - Typing Challenge
  {
    id: 43,
    type: "minigame_typing",
    title: "Rapid Transcription",
    story: "Level 43: Type faster than time itself.",
    question: "Type the text 'chronocipher' as quickly as possible",
    answer: "VICTORY",
    hint: "Speed and accuracy matter.",
    clue: "VELOCITY",
    time: 90,
    difficulty: "hard",
    textToType: "chronocipher",
  },
];

export const getPuzzleById = (id) => {
  return puzzles.find((p) => p.id === id);
};

export const isMiniGame = (puzzle) => {
  return puzzle?.type?.startsWith("minigame_");
};
